In [ ]:
#@title Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
# https://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.

**Note:** This notebook can run using TensorFlow 2.5.0

In [ ]:
#!pip install tensorflow==2.5.0

In [ ]:
import tensorflow as tf
import numpy as np
import matplotlib.pyplot as plt
print(tf.__version__)

In [ ]:
dataset = tf.data.Dataset.range(10)
for val in dataset:
   print(val.numpy())

# 예
# 0
# 1
# 2
# 3
# 4
# 5
# 6
# 7
# 8
# 9

In [ ]:
dataset = tf.data.Dataset.range(10)
dataset = dataset.window(5, shift=1)
for window_dataset in dataset:
   for val in window_dataset:
     print(val.numpy(), end = " ")
   print()

# 예

# 0 1 2 3 4 
# 1 2 3 4 5 
# 2 3 4 5 6 
# 3 4 5 6 7 
# 4 5 6 7 8 
# 5 6 7 8 9 
# 6 7 8 9 
# 7 8 9 
# 8 9 
# 9 

In [ ]:
dataset = tf.data.Dataset.range(10)
dataset = dataset.window(5, shift=1)
for window_dataset in dataset:
  for val in window_dataset:
    print(val.numpy(), end=" ")
  print()

In [ ]:
dataset = tf.data.Dataset.range(10)
dataset = dataset.window(5, shift=1, drop_remainder=True)
for window_dataset in dataset:
  for val in window_dataset:
    print(val.numpy(), end=" ")
  print()

# 그냥 dataset 안을 window_dataset으로 loop 돌려서 보면 이렇게 나온다.
# <_VariantDataset shapes: (), types: tf.int64>
# <_VariantDataset shapes: (), types: tf.int64>
# <_VariantDataset shapes: (), types: tf.int64>
# <_VariantDataset shapes: (), types: tf.int64>
# <_VariantDataset shapes: (), types: tf.int64>
# <_VariantDataset shapes: (), types: tf.int64>

# 결과
# 0 1 2 3 4 
# 1 2 3 4 5 
# 2 3 4 5 6 
# 3 4 5 6 7 
# 4 5 6 7 8 
# 5 6 7 8 9

In [ ]:
dataset = tf.data.Dataset.range(10)
dataset = dataset.window(5, shift=1, drop_remainder=True)
dataset = dataset.flat_map(lambda window: window.batch(5))
for window in dataset:
  print(window.numpy())
# 예
# [0 1 2 3 4]
# [1 2 3 4 5]
# [2 3 4 5 6]
# [3 4 5 6 7]
# [4 5 6 7 8]
# [5 6 7 8 9]

In [ ]:
dataset = tf.data.Dataset.range(10)
dataset = dataset.window(5, shift=1, drop_remainder=True)
dataset = dataset.flat_map(lambda window: window.batch(5))
dataset = dataset.map(lambda window: (window[:-1], window[-1:]))
for x,y in dataset:
  print(x.numpy(), y.numpy())

# 예
# [0 1 2 3] [4]
# [1 2 3 4] [5]
# [2 3 4 5] [6]
# [3 4 5 6] [7]
# [4 5 6 7] [8]
# [5 6 7 8] [9]

In [ ]:
dataset = tf.data.Dataset.range(10)
dataset = dataset.window(5, shift=1, drop_remainder=True)
dataset = dataset.flat_map(lambda window: window.batch(5))
dataset = dataset.map(lambda window: (window[:-1], window[-1:]))
dataset = dataset.shuffle(buffer_size=10) #데이터 갯수와 동일하거나 더 커야함. 작으면 초반 N까지만 shuffle하고 뒤는 안되게되므로..
for x,y in dataset:
  print(x.numpy(), y.numpy())

# 예
# [5 6 7 8] [9]
# [2 3 4 5] [6]
# [3 4 5 6] [7]
# [0 1 2 3] [4]
# [1 2 3 4] [5]
# [4 5 6 7] [8]


In [ ]:
dataset = tf.data.Dataset.range(10)
dataset = dataset.window(5, shift=1, drop_remainder=True)
dataset = dataset.flat_map(lambda window: window.batch(5))
dataset = dataset.map(lambda window: (window[:-1], window[-1:]))
dataset = dataset.shuffle(buffer_size=10)
dataset = dataset.batch(2).prefetch(1) #x, y를 배치사이즈에 맞게 묶어서 만들어준다.
for x,y in dataset:
  print("x = ", x.numpy())
  print("y = ", y.numpy())

 # 예
#x =  [[1 2 3 4]
# [4 5 6 7]]
#y =  [[5]
# [8]]
#x =  [[0 1 2 3]
# [2 3 4 5]]
#y =  [[4]
# [6]]
#x =  [[5 6 7 8]
# [3 4 5 6]]
#y =  [[9]
# [7]]
